#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  3 23:49:32 2019

@author: lupeiqing
"""
import pandas as pd
import operator
arts=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/arts.csv")
community=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/community.csv")
housing=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/housing.csv")
library=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/library.csv")
program=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/program.csv")
resident=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/resident.csv")
school=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/school.csv")
services=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/services.csv")
street=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/street.csv")
youth=pd.read_csv("/Users/lupeiqing/Desktop/cs506/twitter_process/youth.csv")
word_map={}
for i in arts['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in community['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in housing['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in library['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in program['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in resident['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in school['hashtag']:
    i=str(i).replace("[","")
    i=str(i).replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in map_word:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in services['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in word_map:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in street['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in word_map:
            map_word[i]+=1
        else:
            map_word[i]=0
for i in youth['hashtag']:
    i=i.replace("[","")
    i=i.replace("]","")
    tag_list=i.split(",")
    for i in tag_list:
        if i in word_map:
            map_word[i]+=1
        else:
            map_word[i]=0
sorted_list = sorted(map_word.items(), key=operator.itemgetter(1))
print(sorted_list)